import os

VERSION = "1.0"
SLACK_BOT_TOKEN = os.environ.get('SLACK_BOT_TOKEN')
SLACK_USER_ACCESS_TOKEN = os.environ.get('SLACK_USER_ACCESS_TOKEN')

COFFEE_SLACK_CHANNEL = "coffee"
COFFEE_UPDATE_INTERVAL_IN_MS = 10000

COFFEE_FULL_THRESHOLD = 1020000
COFFEE_EMPTY_OR_LOW_THRESHOLD = 810000
COFFEE_FULL_FILENAME = "coffee-full.png"
COFFEE_FULL_MESSAGE = "*HOT COFFEE IS READY!*"
COFFEE_NEEDS_ATTENTION_FILENAME = "coffee-low.png"
COFFEE_NEEDS_ATTENTION_MESSAGE = "**** *WARNING! COFFEE POT IS LOW OR EMPTY* ****"

